# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: grafana.aws.m.upbound.io/v1beta1
kind: WorkspaceServiceAccountToken
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1beta1/workspaceserviceaccounttoken
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    name: example-key
    region: us-west-1
    secondsToLive: 3600
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    workspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: grafana.aws.m.upbound.io/v1beta1
kind: WorkspaceServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1beta1/workspaceserviceaccounttoken
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    grafanaRole: ADMIN
    name: example-admin
    region: us-west-1
    workspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
