# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cloudwatchlogs.aws.m.upbound.io/v1beta1
kind: AccountPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: cloudwatchlogs/v1beta1/accountpolicy
    upjet.upbound.io/manual-intervention: This resource needs a JSON inline reference replacement (policyDocument field)
  labels:
    testing.upbound.io/example-name: subscription-filter-policy
  name: subscription-filter-policy
  namespace: upbound-system
spec:
  forProvider:
    region: us-west-1
    policyType: SUBSCRIPTION_FILTER_POLICY
    policyDocument: |
      {
        "DestinationArn": "arn:aws:lambda:us-west-1:153891904029:function:cloudwatchlogs",
        "FilterPattern": "test"
      }
    selectionCriteria: 'LogGroupName NOT IN ["excluded_log_group_name"]'
