# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cloudwatchlogs.aws.m.upbound.io/v1beta1
kind: DeliveryDestination
metadata:
  annotations:
    meta.upbound.io/example-id: cloudwatchlogs/v1beta1/deliverydestination
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    region: us-east-1
    name: example-delivery-destination
    outputFormat: json
    deliveryDestinationConfiguration:
      destinationResourceArnSelector:
        matchLabels:
          testing.upbound.io/example-name: example

---

apiVersion: cloudwatchlogs.aws.m.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: cloudwatchlogs/v1beta1/deliverydestination
  labels:
    testing.upbound.io/example-name: example
  name: example-deliverydestination
  namespace: upbound-system
spec:
  forProvider:
    region: us-east-1
    retentionInDays: 1
