# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: codebuild.aws.upbound.io/v1beta1
kind: SourceCredential
metadata:
  name: example
  annotations:
    meta.upbound.io/example-id: codebuild/v1beta1/sourcecredential
  labels:
    testing.upbound.io/example-name: example-codebuild-sourcecredential
spec:
  forProvider:
    region: us-west-1
    authType: PERSONAL_ACCESS_TOKEN
    serverType: GITHUB
    tokenSecretRef:
      key: token
      name: github-token
      namespace: upbound-system
