apiVersion: batch.aws.upbound.io/v1beta1
kind: JobQueue
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue
  name: test-queue
spec:
  forProvider:
    computeEnvironmentOrder:
      - computeEnvironmentSelector:
          matchLabels:
            testing.upbound.io/example-name: example-jobqueue
        order: 1
    priority: 1
    region: us-west-1
    state: ENABLED
---
apiVersion: batch.aws.upbound.io/v1beta1
kind: ComputeEnvironment
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue
  name: example-ec2-compute-environment
spec:
  forProvider:
    computeResources:
      instanceRoleSelector:
        matchLabels:
          testing.upbound.io/example-name: example-jobqueue
      instanceType:
        - c4.large
      maxVcpus: 4
      minVcpus: 0
      placementGroupSelector:
        matchLabels:
          testing.upbound.io/example-name: example-jobqueue
      securityGroupIdsSelector:
        matchLabels:
          testing.upbound.io/example-name: example-jobqueue
      subnetsSelector:
        matchLabels:
          testing.upbound.io/example-name: example-jobqueue
      type: EC2
    region: us-west-1
    serviceRoleSelector:
      matchLabels:
        testing.upbound.io/example-name: example-jobqueue-batch-service-role
    type: MANAGED
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: InstanceProfile
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue
  name: example-ecs-instance-profile-jobqueue
spec:
  forProvider:
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: example-jobqueue-ecs-role
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue-ecs-role
  name: example-ecs-instance-role-jobqueue
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue-ecs-role-attachment
  name: example-ecs-instance-role-attachment-jobqueue
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: example-jobqueue-ecs-role
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue-batch-service-role
  name: example-batch-service-role-jobqueue
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "batch.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue-batch-service-role-attachment
  name: example-batch-service-role-attachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: example-jobqueue-batch-service-role
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: PlacementGroup
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue
  name: example-placement-group
spec:
  forProvider:
    region: us-west-1
    strategy: cluster
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue
  name: example-sg
spec:
  forProvider:
    region: us-west-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-jobqueue
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue
  name: example-subnet
spec:
  forProvider:
    cidrBlock: 10.1.1.0/24
    region: us-west-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-jobqueue
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: batch/v1beta1/jobqueue
  labels:
    testing.upbound.io/example-name: example-jobqueue
  name: example-vpc
spec:
  forProvider:
    cidrBlock: 10.1.0.0/16
    region: us-west-1
---
apiVersion: protection.crossplane.io/v1beta1
kind: ClusterUsage
metadata:
  annotations:
    "uptest.upbound.io/conditions": "Ready"
    "uptest.upbound.io/disable-import": "true"
  name: compute-env-uses-role
spec:
  replayDeletion: true
  by:
    apiVersion: batch.aws.upbound.io/v1beta1
    kind: ComputeEnvironment
    resourceSelector:
      matchLabels:
        testing.upbound.io/example-name: example-jobqueue
  of:
    apiVersion: iam.aws.upbound.io/v1beta1
    kind: Role
    resourceSelector:
      matchLabels:
        testing.upbound.io/example-name: example-jobqueue-batch-service-role
---
apiVersion: protection.crossplane.io/v1beta1
kind: ClusterUsage
metadata:
  annotations:
    "uptest.upbound.io/conditions": "Ready"
    "uptest.upbound.io/disable-import": "true"
  name: compute-env-uses-role-binding
spec:
  replayDeletion: true
  by:
    apiVersion: batch.aws.upbound.io/v1beta1
    kind: ComputeEnvironment
    resourceSelector:
      matchLabels:
        testing.upbound.io/example-name: example-jobqueue
  of:
    apiVersion: iam.aws.upbound.io/v1beta1
    kind: RolePolicyAttachment
    resourceSelector:
      matchLabels:
        testing.upbound.io/example-name: example-jobqueue-batch-service-role-attachment
