// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: CC0-1.0

package namespaced

import (
	"github.com/upbound/provider-aws/v2/config/namespaced/acm"
	"github.com/upbound/provider-aws/v2/config/namespaced/acmpca"
	"github.com/upbound/provider-aws/v2/config/namespaced/amp"
	"github.com/upbound/provider-aws/v2/config/namespaced/apigateway"
	"github.com/upbound/provider-aws/v2/config/namespaced/apigatewayv2"
	"github.com/upbound/provider-aws/v2/config/namespaced/apprunner"
	"github.com/upbound/provider-aws/v2/config/namespaced/appstream"
	"github.com/upbound/provider-aws/v2/config/namespaced/athena"
	"github.com/upbound/provider-aws/v2/config/namespaced/autoscaling"
	"github.com/upbound/provider-aws/v2/config/namespaced/backup"
	"github.com/upbound/provider-aws/v2/config/namespaced/batch"
	"github.com/upbound/provider-aws/v2/config/namespaced/budgets"
	"github.com/upbound/provider-aws/v2/config/namespaced/cloudformation"
	"github.com/upbound/provider-aws/v2/config/namespaced/cloudfront"
	"github.com/upbound/provider-aws/v2/config/namespaced/cloudsearch"
	"github.com/upbound/provider-aws/v2/config/namespaced/cloudwatch"
	"github.com/upbound/provider-aws/v2/config/namespaced/cloudwatchevents"
	"github.com/upbound/provider-aws/v2/config/namespaced/cloudwatchlogs"
	"github.com/upbound/provider-aws/v2/config/namespaced/codeartifact"
	"github.com/upbound/provider-aws/v2/config/namespaced/cognitoidentity"
	"github.com/upbound/provider-aws/v2/config/namespaced/cognitoidp"
	"github.com/upbound/provider-aws/v2/config/namespaced/connect"
	"github.com/upbound/provider-aws/v2/config/namespaced/cur"
	"github.com/upbound/provider-aws/v2/config/namespaced/datasync"
	"github.com/upbound/provider-aws/v2/config/namespaced/dax"
	"github.com/upbound/provider-aws/v2/config/namespaced/devicefarm"
	"github.com/upbound/provider-aws/v2/config/namespaced/directconnect"
	"github.com/upbound/provider-aws/v2/config/namespaced/dms"
	"github.com/upbound/provider-aws/v2/config/namespaced/docdb"
	"github.com/upbound/provider-aws/v2/config/namespaced/ds"
	"github.com/upbound/provider-aws/v2/config/namespaced/dsql"
	"github.com/upbound/provider-aws/v2/config/namespaced/dynamodb"
	"github.com/upbound/provider-aws/v2/config/namespaced/ebs"
	"github.com/upbound/provider-aws/v2/config/namespaced/ec2"
	"github.com/upbound/provider-aws/v2/config/namespaced/ecr"
	"github.com/upbound/provider-aws/v2/config/namespaced/ecrpublic"
	"github.com/upbound/provider-aws/v2/config/namespaced/ecs"
	"github.com/upbound/provider-aws/v2/config/namespaced/efs"
	"github.com/upbound/provider-aws/v2/config/namespaced/eks"
	"github.com/upbound/provider-aws/v2/config/namespaced/elasticache"
	"github.com/upbound/provider-aws/v2/config/namespaced/elb"
	"github.com/upbound/provider-aws/v2/config/namespaced/elbv2"
	"github.com/upbound/provider-aws/v2/config/namespaced/firehose"
	"github.com/upbound/provider-aws/v2/config/namespaced/fsx"
	"github.com/upbound/provider-aws/v2/config/namespaced/gamelift"
	"github.com/upbound/provider-aws/v2/config/namespaced/globalaccelerator"
	"github.com/upbound/provider-aws/v2/config/namespaced/glue"
	"github.com/upbound/provider-aws/v2/config/namespaced/grafana"
	"github.com/upbound/provider-aws/v2/config/namespaced/iam"
	"github.com/upbound/provider-aws/v2/config/namespaced/identitystore"
	"github.com/upbound/provider-aws/v2/config/namespaced/iot"
	"github.com/upbound/provider-aws/v2/config/namespaced/kafka"
	"github.com/upbound/provider-aws/v2/config/namespaced/kafkaconnect"
	"github.com/upbound/provider-aws/v2/config/namespaced/kendra"
	"github.com/upbound/provider-aws/v2/config/namespaced/kinesis"
	"github.com/upbound/provider-aws/v2/config/namespaced/kinesisanalytics"
	kinesisanalytics2 "github.com/upbound/provider-aws/v2/config/namespaced/kinesisanalyticsv2"
	"github.com/upbound/provider-aws/v2/config/namespaced/kms"
	"github.com/upbound/provider-aws/v2/config/namespaced/lakeformation"
	"github.com/upbound/provider-aws/v2/config/namespaced/lambda"
	"github.com/upbound/provider-aws/v2/config/namespaced/licensemanager"
	"github.com/upbound/provider-aws/v2/config/namespaced/medialive"
	"github.com/upbound/provider-aws/v2/config/namespaced/memorydb"
	"github.com/upbound/provider-aws/v2/config/namespaced/mq"
	"github.com/upbound/provider-aws/v2/config/namespaced/mwaa"
	"github.com/upbound/provider-aws/v2/config/namespaced/neptune"
	"github.com/upbound/provider-aws/v2/config/namespaced/networkfirewall"
	"github.com/upbound/provider-aws/v2/config/namespaced/networkmanager"
	"github.com/upbound/provider-aws/v2/config/namespaced/opensearch"
	"github.com/upbound/provider-aws/v2/config/namespaced/opensearchserverless"
	"github.com/upbound/provider-aws/v2/config/namespaced/organization"
	"github.com/upbound/provider-aws/v2/config/namespaced/qldb"
	"github.com/upbound/provider-aws/v2/config/namespaced/ram"
	"github.com/upbound/provider-aws/v2/config/namespaced/rds"
	"github.com/upbound/provider-aws/v2/config/namespaced/redshift"
	"github.com/upbound/provider-aws/v2/config/namespaced/redshiftserverless"
	"github.com/upbound/provider-aws/v2/config/namespaced/rolesanywhere"
	"github.com/upbound/provider-aws/v2/config/namespaced/route53"
	"github.com/upbound/provider-aws/v2/config/namespaced/route53recoverycontrolconfig"
	"github.com/upbound/provider-aws/v2/config/namespaced/route53resolver"
	"github.com/upbound/provider-aws/v2/config/namespaced/s3"
	"github.com/upbound/provider-aws/v2/config/namespaced/sagemaker"
	"github.com/upbound/provider-aws/v2/config/namespaced/secretsmanager"
	"github.com/upbound/provider-aws/v2/config/namespaced/servicecatalog"
	"github.com/upbound/provider-aws/v2/config/namespaced/servicediscovery"
	"github.com/upbound/provider-aws/v2/config/namespaced/sfn"
	"github.com/upbound/provider-aws/v2/config/namespaced/sns"
	"github.com/upbound/provider-aws/v2/config/namespaced/sqs"
	"github.com/upbound/provider-aws/v2/config/namespaced/ssoadmin"
	"github.com/upbound/provider-aws/v2/config/namespaced/transfer"
	"github.com/upbound/provider-aws/v2/config/namespaced/verifiedaccess"
	"github.com/upbound/provider-aws/v2/config/namespaced/vpclattice"
	"github.com/upbound/provider-aws/v2/config/namespaced/wafv2"
)

func init() {
	ProviderConfiguration.AddConfig(acm.Configure)
	ProviderConfiguration.AddConfig(acmpca.Configure)
	ProviderConfiguration.AddConfig(amp.Configure)
	ProviderConfiguration.AddConfig(apigateway.Configure)
	ProviderConfiguration.AddConfig(apigatewayv2.Configure)
	ProviderConfiguration.AddConfig(apprunner.Configure)
	ProviderConfiguration.AddConfig(appstream.Configure)
	ProviderConfiguration.AddConfig(athena.Configure)
	ProviderConfiguration.AddConfig(autoscaling.Configure)
	ProviderConfiguration.AddConfig(backup.Configure)
	ProviderConfiguration.AddConfig(batch.Configure)
	ProviderConfiguration.AddConfig(cloudfront.Configure)
	ProviderConfiguration.AddConfig(cloudsearch.Configure)
	ProviderConfiguration.AddConfig(cloudwatch.Configure)
	ProviderConfiguration.AddConfig(cloudwatchlogs.Configure)
	ProviderConfiguration.AddConfig(codeartifact.Configure)
	ProviderConfiguration.AddConfig(cognitoidentity.Configure)
	ProviderConfiguration.AddConfig(cognitoidp.Configure)
	ProviderConfiguration.AddConfig(connect.Configure)
	ProviderConfiguration.AddConfig(cur.Configure)
	ProviderConfiguration.AddConfig(datasync.Configure)
	ProviderConfiguration.AddConfig(dax.Configure)
	ProviderConfiguration.AddConfig(devicefarm.Configure)
	ProviderConfiguration.AddConfig(dms.Configure)
	ProviderConfiguration.AddConfig(docdb.Configure)
	ProviderConfiguration.AddConfig(dynamodb.Configure)
	ProviderConfiguration.AddConfig(ebs.Configure)
	ProviderConfiguration.AddConfig(ec2.Configure)
	ProviderConfiguration.AddConfig(ecr.Configure)
	ProviderConfiguration.AddConfig(ecrpublic.Configure)
	ProviderConfiguration.AddConfig(ecs.Configure)
	ProviderConfiguration.AddConfig(efs.Configure)
	ProviderConfiguration.AddConfig(eks.Configure)
	ProviderConfiguration.AddConfig(elasticache.Configure)
	ProviderConfiguration.AddConfig(elb.Configure)
	ProviderConfiguration.AddConfig(elbv2.Configure)
	ProviderConfiguration.AddConfig(firehose.Configure)
	ProviderConfiguration.AddConfig(gamelift.Configure)
	ProviderConfiguration.AddConfig(globalaccelerator.Configure)
	ProviderConfiguration.AddConfig(glue.Configure)
	ProviderConfiguration.AddConfig(grafana.Configure)
	ProviderConfiguration.AddConfig(iam.Configure)
	ProviderConfiguration.AddConfig(kafka.Configure)
	ProviderConfiguration.AddConfig(kafkaconnect.Configure)
	ProviderConfiguration.AddConfig(kinesis.Configure)
	ProviderConfiguration.AddConfig(kinesisanalytics.Configure)
	ProviderConfiguration.AddConfig(kinesisanalytics2.Configure)
	ProviderConfiguration.AddConfig(kms.Configure)
	ProviderConfiguration.AddConfig(lakeformation.Configure)
	ProviderConfiguration.AddConfig(lambda.Configure)
	ProviderConfiguration.AddConfig(licensemanager.Configure)
	ProviderConfiguration.AddConfig(memorydb.Configure)
	ProviderConfiguration.AddConfig(mq.Configure)
	ProviderConfiguration.AddConfig(mwaa.Configure)
	ProviderConfiguration.AddConfig(neptune.Configure)
	ProviderConfiguration.AddConfig(networkfirewall.Configure)
	ProviderConfiguration.AddConfig(opensearch.Configure)
	ProviderConfiguration.AddConfig(opensearchserverless.Configure)
	ProviderConfiguration.AddConfig(ram.Configure)
	ProviderConfiguration.AddConfig(rds.Configure)
	ProviderConfiguration.AddConfig(redshift.Configure)
	ProviderConfiguration.AddConfig(rolesanywhere.Configure)
	ProviderConfiguration.AddConfig(route53.Configure)
	ProviderConfiguration.AddConfig(route53resolver.Configure)
	ProviderConfiguration.AddConfig(route53recoverycontrolconfig.Configure)
	ProviderConfiguration.AddConfig(s3.Configure)
	ProviderConfiguration.AddConfig(secretsmanager.Configure)
	ProviderConfiguration.AddConfig(servicecatalog.Configure)
	ProviderConfiguration.AddConfig(organization.Configure)
	ProviderConfiguration.AddConfig(cloudwatchevents.Configure)
	ProviderConfiguration.AddConfig(budgets.Configure)
	ProviderConfiguration.AddConfig(servicediscovery.Configure)
	ProviderConfiguration.AddConfig(sfn.Configure)
	ProviderConfiguration.AddConfig(sns.Configure)
	ProviderConfiguration.AddConfig(sqs.Configure)
	ProviderConfiguration.AddConfig(transfer.Configure)
	ProviderConfiguration.AddConfig(directconnect.Configure)
	ProviderConfiguration.AddConfig(ds.Configure)
	ProviderConfiguration.AddConfig(dsql.Configure)
	ProviderConfiguration.AddConfig(qldb.Configure)
	ProviderConfiguration.AddConfig(fsx.Configure)
	ProviderConfiguration.AddConfig(networkmanager.Configure)
	ProviderConfiguration.AddConfig(sagemaker.Configure)
	ProviderConfiguration.AddConfig(redshiftserverless.Configure)
	ProviderConfiguration.AddConfig(kendra.Configure)
	ProviderConfiguration.AddConfig(medialive.Configure)
	ProviderConfiguration.AddConfig(ssoadmin.Configure)
	ProviderConfiguration.AddConfig(identitystore.Configure)
	ProviderConfiguration.AddConfig(iot.Configure)
	ProviderConfiguration.AddConfig(cloudformation.Configure)
	ProviderConfiguration.AddConfig(wafv2.Configure)
	ProviderConfiguration.AddConfig(verifiedaccess.Configure)
	ProviderConfiguration.AddConfig(vpclattice.Configure)
}
