# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cloudwatchevents.aws.upbound.io/v1beta1
kind: Bus
metadata:
  annotations:
    meta.upbound.io/example-id: cloudwatchevents/v1beta1/bus
  name: messenger
spec:
  forProvider:
    region: us-west-1
