# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

# Guardrail Version Example
# Creates a version of a Bedrock guardrail.

apiVersion: bedrock.aws.upbound.io/v1beta1
kind: GuardrailVersion
metadata:
  annotations:
    meta.upbound.io/example-id: bedrock/v1beta1/guardrailversion
  labels:
    testing.upbound.io/example-name: guardrailversion
  name: guardrailversion
spec:
  forProvider:
    description: example
    guardrailArnSelector:
      matchLabels:
        testing.upbound.io/example-name: guardrailversion
    region: us-east-1

---

apiVersion: bedrock.aws.upbound.io/v1beta1
kind: Guardrail
metadata:
  annotations:
    meta.upbound.io/example-id: bedrock/v1beta1/guardrailversion
  labels:
    testing.upbound.io/example-name: guardrailversion
  name: guardrailversion
spec:
  forProvider:
    blockedInputMessaging: example
    blockedOutputsMessaging: example
    contentPolicyConfig:
      filtersConfig:
        - inputStrength: MEDIUM
          outputStrength: MEDIUM
          type: HATE
      tierConfig:
        tierName: CLASSIC
    description: example
    name: example-guardrail-version
    region: us-east-1
