# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: grafana.aws.upbound.io/v1beta1
kind: WorkspaceServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1beta1/workspaceserviceaccount
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    grafanaRole: ADMIN
    name: example-admin
    region: us-west-1
    workspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
