# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: codebuild.aws.m.upbound.io/v1beta1
kind: SourceCredential
metadata:
  annotations:
    meta.upbound.io/example-id: codebuild/v1beta1/sourcecredential
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    authType: PERSONAL_ACCESS_TOKEN
    region: us-west-1
    serverType: GITHUB
    tokenSecretRef:
      key: example-key
      name: example-secret
