// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type IdentityPolicyInitParameters struct {

	// Name or Amazon Resource Name (ARN) of the SES Identity.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/cluster/ses/v1beta1.DomainIdentity
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	Identity *string `json:"identity,omitempty" tf:"identity,omitempty"`

	// Reference to a DomainIdentity in ses to populate identity.
	// +kubebuilder:validation:Optional
	IdentityRef *v1.Reference `json:"identityRef,omitempty" tf:"-"`

	// Selector for a DomainIdentity in ses to populate identity.
	// +kubebuilder:validation:Optional
	IdentitySelector *v1.Selector `json:"identitySelector,omitempty" tf:"-"`

	// Name of the policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// JSON string of the policy.
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`
}

type IdentityPolicyObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name or Amazon Resource Name (ARN) of the SES Identity.
	Identity *string `json:"identity,omitempty" tf:"identity,omitempty"`

	// Name of the policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// JSON string of the policy.
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type IdentityPolicyParameters struct {

	// Name or Amazon Resource Name (ARN) of the SES Identity.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/cluster/ses/v1beta1.DomainIdentity
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	// +kubebuilder:validation:Optional
	Identity *string `json:"identity,omitempty" tf:"identity,omitempty"`

	// Reference to a DomainIdentity in ses to populate identity.
	// +kubebuilder:validation:Optional
	IdentityRef *v1.Reference `json:"identityRef,omitempty" tf:"-"`

	// Selector for a DomainIdentity in ses to populate identity.
	// +kubebuilder:validation:Optional
	IdentitySelector *v1.Selector `json:"identitySelector,omitempty" tf:"-"`

	// Name of the policy.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// JSON string of the policy.
	// +kubebuilder:validation:Optional
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`
}

// IdentityPolicySpec defines the desired state of IdentityPolicy
type IdentityPolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IdentityPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IdentityPolicyInitParameters `json:"initProvider,omitempty"`
}

// IdentityPolicyStatus defines the observed state of IdentityPolicy.
type IdentityPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IdentityPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IdentityPolicy is the Schema for the IdentityPolicys API. Manages a SES Identity Policy
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type IdentityPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.policy) || (has(self.initProvider) && has(self.initProvider.policy))",message="spec.forProvider.policy is a required parameter"
	Spec   IdentityPolicySpec   `json:"spec"`
	Status IdentityPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IdentityPolicyList contains a list of IdentityPolicys
type IdentityPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IdentityPolicy `json:"items"`
}

// Repository type metadata.
var (
	IdentityPolicy_Kind             = "IdentityPolicy"
	IdentityPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IdentityPolicy_Kind}.String()
	IdentityPolicy_KindAPIVersion   = IdentityPolicy_Kind + "." + CRDGroupVersion.String()
	IdentityPolicy_GroupVersionKind = CRDGroupVersion.WithKind(IdentityPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&IdentityPolicy{}, &IdentityPolicyList{})
}
