# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: athena.aws.upbound.io/v1beta1
kind: NamedQuery
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "TODO: needs resource dependencies added"
    meta.upbound.io/example-id: athena/v1beta1/namedquery
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    databaseSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: bar
    query: SELECT * FROM example limit 10;
    region: us-west-1
    workgroupSelector:
      matchLabels:
        testing.upbound.io/example-name: test
