# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: bedrockagentcore.aws.m.upbound.io/v1beta1
kind: APIKeyCredentialProvider
metadata:
  annotations:
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/apikeycredentialprovider
  labels:
    testing.upbound.io/example-name: apikeycredentialprovider-cms
  name: apikeycredentialprovider-cms
  namespace: upbound-system
spec:
  forProvider:
    region: us-west-2
    apiKeySecretSource: EXTERNAL
    apiKeySecretConfig:
      secretIdSelector:
        matchLabels:
          testing.upbound.io/example-name: apikeycredentialprovider-cms
      jsonKey: test
    tags:
      Environment: Demo
---
apiVersion: secretsmanager.aws.m.upbound.io/v1beta1
kind: Secret
metadata:
  name: example-cms
  namespace: upbound-system
  annotations:
    uptest.upbound.io/disable-import: "true"
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/apikeycredentialprovider
  labels:
    testing.upbound.io/example-name: apikeycredentialprovider-cms
spec:
  forProvider:
    name: example-${Rand.RFC1123Subdomain}
    region: us-west-2
    recoveryWindowInDays: 0
---
apiVersion: secretsmanager.aws.m.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: example-cms-version
  namespace: upbound-system
  annotations:
    uptest.upbound.io/disable-import: "true"
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/apikeycredentialprovider
  labels:
    testing.upbound.io/example-name: apikeycredentialprovider-cms
spec:
  forProvider:
    region: us-west-2
    secretIdSelector:
      matchLabels:
        testing.upbound.io/example-name: apikeycredentialprovider-cms
    secretStringSecretRef:
      key: demo
      name: example-secret-version
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret-version
  namespace: upbound-system
type: Opaque
stringData:
  demo: '{"test": "Test12345!"}'