# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

# GitHub OAuth Provider Example

apiVersion: bedrockagentcore.aws.m.upbound.io/v1beta1
kind: Oauth2CredentialProvider
metadata:
  annotations:
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/oauth2credentialprovider
    crossplane.io/external-name: github-oauth-provider
  labels:
    testing.upbound.io/example-name: oauth2credentialprovider-cms
  name: oauth2credentialprovider-cms
  namespace: upbound-system
spec:
  forProvider:
    region: us-west-2
    credentialProviderVendor: GithubOauth2
    oauth2ProviderConfig:
      githubOauth2ProviderConfig:
        clientSecretSource: EXTERNAL
        clientIdSecretRef:
          key: client-id
          name: example-secret-version
        clientSecretConfig:
          secretIdSelector:
            matchLabels:
              testing.upbound.io/example-name: oauth2credentialprovider-cms
          jsonKey: test
---
apiVersion: secretsmanager.aws.m.upbound.io/v1beta1
kind: Secret
metadata:
  name: example-cms
  namespace: upbound-system
  annotations:
    uptest.upbound.io/disable-import: "true"
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/oauth2credentialprovider
  labels:
    testing.upbound.io/example-name: oauth2credentialprovider-cms
spec:
  forProvider:
    name: example-brac
    region: us-west-2
    recoveryWindowInDays: 0
---
apiVersion: secretsmanager.aws.m.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: example-cms-version
  namespace: upbound-system
  annotations:
    uptest.upbound.io/disable-import: "true"
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/oauth2credentialprovider
  labels:
    testing.upbound.io/example-name: oauth2credentialprovider-cms
spec:
  forProvider:
    region: us-west-2
    secretIdSelector:
      matchLabels:
        testing.upbound.io/example-name: oauth2credentialprovider-cms
    secretStringSecretRef:
      key: demo
      name: example-secret-version
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret-version
  namespace: upbound-system
type: Opaque
stringData:
  demo: '{"test": "Test12345!"}'
  client-id: "test-client-oauth"