# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

# GitHub OAuth Provider Example

apiVersion: bedrockagentcore.aws.m.upbound.io/v1beta1
kind: Oauth2CredentialProvider
metadata:
  annotations:
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/oauth2credentialprovider
    crossplane.io/external-name: github-oauth-provider
  labels:
    testing.upbound.io/example-name: oauth2credentialprovider
  name: oauth2credentialprovider
  namespace: upbound-system
spec:
  forProvider:
    region: us-west-2
    credentialProviderVendor: GithubOauth2
    oauth2ProviderConfig:
      githubOauth2ProviderConfig:
        clientIdSecretRef:
          key: client-id
          name: test-oauth-credentials
        clientSecretSecretRef:
          key: client-secret
          name: test-oauth-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: test-oauth-credentials
  namespace: upbound-system
stringData:
  client-id: "test-client-oauth"
  client-secret: "T0ps3cr3t!"