# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: timestreaminfluxdb.aws.m.upbound.io/v1beta1
kind: DBCluster
metadata:
  annotations:
    meta.upbound.io/example-id: timestreaminfluxdb/v1beta1/dbcluster
    upjet.upbound.io/manual-intervention: Requires an active subscription for InfluxDB Read Replicas from AWS Marketplace
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    allocatedStorage: 20
    bucket: example-bucket-name
    dbInstanceType: db.influx.medium
    failoverMode: AUTOMATIC
    name: example-db-cluster
    organization: organization
    passwordSecretRef:
      key: password
      name: influxdb-password
      namespace: upbound-system
    port: 8086
    region: us-east-1
    username: admin
    vpcSecurityGroupIdsRefs:
    - name: example
    vpcSubnetIdsRefs:
    - name: example-1
    - name: example-2
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---

apiVersion: v1
kind: Secret
metadata:
  name: influxdb-password
  namespace: upbound-system
type: Opaque
stringData:
  password: TestPass123

---

apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: timestreaminfluxdb/v1beta1/dbcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    region: us-east-1
    description: Security group for InfluxDB cluster
    name: influxdb-cluster-sg
    tags:
      Name: influxdb-cluster-sg
    vpcIdRef:
      name: sample-vpc

---

apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: timestreaminfluxdb/v1beta1/dbcluster
  labels:
    testing.upbound.io/example-name: example-1
  name: example-1
  namespace: upbound-system
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 172.16.10.0/24
    vpcIdRef:
      name: sample-vpc

---

apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: timestreaminfluxdb/v1beta1/dbcluster
  labels:
    testing.upbound.io/example-name: example-2
  name: example-2
  namespace: upbound-system
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1b
    cidrBlock: 172.16.20.0/24
    vpcIdRef:
      name: sample-vpc

---

apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: timestreaminfluxdb/v1beta1/dbcluster
  labels:
    testing.upbound.io/example-name: sample-vpc
  name: sample-vpc
  namespace: upbound-system
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 172.16.0.0/16
    tags:
      Name: influxdb-cluster-vpc
