# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: codebuild.aws.upbound.io/v1beta1
kind: Webhook
metadata:
  annotations:
    meta.upbound.io/example-id: codebuild/v1beta1/webhook
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    buildType: BUILD
    filterGroup:
    - filter:
      - pattern: PUSH
        type: EVENT
      - pattern: master
        type: BASE_REF
    projectNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
