# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: bedrockagentcore.aws.upbound.io/v1beta1
kind: Browser
metadata:
  annotations:
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/browser
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Browser for web data extraction
    name: example-browser
    networkConfiguration:
      networkMode: PUBLIC
    region: us-west-1
