# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: bedrockagentcore.aws.upbound.io/v1beta1
kind: Oauth2CredentialProvider
metadata:
  annotations:
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/oauth2credentialprovider
  labels:
    testing.upbound.io/example-name: github
  name: github
spec:
  forProvider:
    credentialProviderVendor: GithubOauth2
    oauth2ProviderConfig:
      githubOauth2ProviderConfig:
        clientIdSecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
        clientSecretSecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
    region: us-west-1
