# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: bedrockagentcore.aws.upbound.io/v1beta1
kind: ResourcePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/resourcepolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    policy: ${data.aws_iam_policy_document.example.json}
    region: us-west-1
    resourceArn: ${aws_bedrockagentcore_agent_runtime.example.agent_runtime_arn}

---

apiVersion: bedrockagentcore.aws.upbound.io/v1beta1
kind: AgentRuntime
metadata:
  annotations:
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/resourcepolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
