# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: bedrockagentcore.aws.upbound.io/v1beta1
kind: WorkloadIdentity
metadata:
  annotations:
    meta.upbound.io/example-id: bedrockagentcore/v1beta1/workloadidentity
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    allowedResourceOauth2ReturnUrls:
    - https://example.com/callback
    region: us-west-1
