# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: lambdamicrovms.aws.m.upbound.io/v1beta1
kind: MicroVM
metadata:
  annotations:
    meta.upbound.io/example-id: lambdamicrovms/v1beta1/microvm
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    imageArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
