# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: s3.aws.upbound.io/v1beta2
kind: BucketAnalyticsConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta2/bucketanalyticsconfiguration
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: s3
    name: EntireBucket
    region: us-west-1
    storageClassAnalysis:
      dataExport:
        destination:
          s3BucketDestination:
            bucketArnSelector:
              matchLabels:
                testing.upbound.io/example-name: s3

---

apiVersion: s3.aws.upbound.io/v1beta2
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta2/bucketanalyticsconfiguration
  labels:
    testing.upbound.io/example-name: s3
  name: s3-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    region: us-west-1
