// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: CC0-1.0

package cluster

import (
	"github.com/upbound/provider-aws/config/cluster/acm"
	"github.com/upbound/provider-aws/config/cluster/acmpca"
	"github.com/upbound/provider-aws/config/cluster/amp"
	"github.com/upbound/provider-aws/config/cluster/apigateway"
	"github.com/upbound/provider-aws/config/cluster/apigatewayv2"
	"github.com/upbound/provider-aws/config/cluster/apprunner"
	"github.com/upbound/provider-aws/config/cluster/appstream"
	"github.com/upbound/provider-aws/config/cluster/athena"
	"github.com/upbound/provider-aws/config/cluster/autoscaling"
	"github.com/upbound/provider-aws/config/cluster/backup"
	"github.com/upbound/provider-aws/config/cluster/batch"
	"github.com/upbound/provider-aws/config/cluster/budgets"
	"github.com/upbound/provider-aws/config/cluster/cloudformation"
	"github.com/upbound/provider-aws/config/cluster/cloudfront"
	"github.com/upbound/provider-aws/config/cluster/cloudsearch"
	"github.com/upbound/provider-aws/config/cluster/cloudwatch"
	"github.com/upbound/provider-aws/config/cluster/cloudwatchevents"
	"github.com/upbound/provider-aws/config/cluster/cloudwatchlogs"
	"github.com/upbound/provider-aws/config/cluster/codeartifact"
	"github.com/upbound/provider-aws/config/cluster/cognitoidentity"
	"github.com/upbound/provider-aws/config/cluster/cognitoidp"
	"github.com/upbound/provider-aws/config/cluster/connect"
	"github.com/upbound/provider-aws/config/cluster/cur"
	"github.com/upbound/provider-aws/config/cluster/datasync"
	"github.com/upbound/provider-aws/config/cluster/dax"
	"github.com/upbound/provider-aws/config/cluster/devicefarm"
	"github.com/upbound/provider-aws/config/cluster/directconnect"
	"github.com/upbound/provider-aws/config/cluster/dms"
	"github.com/upbound/provider-aws/config/cluster/docdb"
	"github.com/upbound/provider-aws/config/cluster/ds"
	"github.com/upbound/provider-aws/config/cluster/dsql"
	"github.com/upbound/provider-aws/config/cluster/dynamodb"
	"github.com/upbound/provider-aws/config/cluster/ebs"
	"github.com/upbound/provider-aws/config/cluster/ec2"
	"github.com/upbound/provider-aws/config/cluster/ecr"
	"github.com/upbound/provider-aws/config/cluster/ecrpublic"
	"github.com/upbound/provider-aws/config/cluster/ecs"
	"github.com/upbound/provider-aws/config/cluster/efs"
	"github.com/upbound/provider-aws/config/cluster/eks"
	"github.com/upbound/provider-aws/config/cluster/elasticache"
	"github.com/upbound/provider-aws/config/cluster/elb"
	"github.com/upbound/provider-aws/config/cluster/elbv2"
	"github.com/upbound/provider-aws/config/cluster/firehose"
	"github.com/upbound/provider-aws/config/cluster/fsx"
	"github.com/upbound/provider-aws/config/cluster/gamelift"
	"github.com/upbound/provider-aws/config/cluster/globalaccelerator"
	"github.com/upbound/provider-aws/config/cluster/glue"
	"github.com/upbound/provider-aws/config/cluster/grafana"
	"github.com/upbound/provider-aws/config/cluster/iam"
	"github.com/upbound/provider-aws/config/cluster/identitystore"
	"github.com/upbound/provider-aws/config/cluster/iot"
	"github.com/upbound/provider-aws/config/cluster/kafka"
	"github.com/upbound/provider-aws/config/cluster/kafkaconnect"
	"github.com/upbound/provider-aws/config/cluster/kendra"
	"github.com/upbound/provider-aws/config/cluster/kinesis"
	"github.com/upbound/provider-aws/config/cluster/kinesisanalytics"
	kinesisanalytics2 "github.com/upbound/provider-aws/config/cluster/kinesisanalyticsv2"
	"github.com/upbound/provider-aws/config/cluster/kms"
	"github.com/upbound/provider-aws/config/cluster/lakeformation"
	"github.com/upbound/provider-aws/config/cluster/lambda"
	"github.com/upbound/provider-aws/config/cluster/licensemanager"
	"github.com/upbound/provider-aws/config/cluster/medialive"
	"github.com/upbound/provider-aws/config/cluster/memorydb"
	"github.com/upbound/provider-aws/config/cluster/mq"
	"github.com/upbound/provider-aws/config/cluster/mwaa"
	"github.com/upbound/provider-aws/config/cluster/neptune"
	"github.com/upbound/provider-aws/config/cluster/networkfirewall"
	"github.com/upbound/provider-aws/config/cluster/networkmanager"
	"github.com/upbound/provider-aws/config/cluster/opensearch"
	"github.com/upbound/provider-aws/config/cluster/opensearchserverless"
	"github.com/upbound/provider-aws/config/cluster/organization"
	"github.com/upbound/provider-aws/config/cluster/qldb"
	"github.com/upbound/provider-aws/config/cluster/ram"
	"github.com/upbound/provider-aws/config/cluster/rds"
	"github.com/upbound/provider-aws/config/cluster/redshift"
	"github.com/upbound/provider-aws/config/cluster/redshiftserverless"
	"github.com/upbound/provider-aws/config/cluster/rolesanywhere"
	"github.com/upbound/provider-aws/config/cluster/route53"
	"github.com/upbound/provider-aws/config/cluster/route53recoverycontrolconfig"
	"github.com/upbound/provider-aws/config/cluster/route53resolver"
	"github.com/upbound/provider-aws/config/cluster/s3"
	"github.com/upbound/provider-aws/config/cluster/sagemaker"
	"github.com/upbound/provider-aws/config/cluster/secretsmanager"
	"github.com/upbound/provider-aws/config/cluster/servicecatalog"
	"github.com/upbound/provider-aws/config/cluster/servicediscovery"
	"github.com/upbound/provider-aws/config/cluster/sfn"
	"github.com/upbound/provider-aws/config/cluster/sns"
	"github.com/upbound/provider-aws/config/cluster/sqs"
	"github.com/upbound/provider-aws/config/cluster/ssoadmin"
	"github.com/upbound/provider-aws/config/cluster/transfer"
	"github.com/upbound/provider-aws/config/cluster/verifiedaccess"
	"github.com/upbound/provider-aws/config/cluster/vpclattice"
	"github.com/upbound/provider-aws/config/cluster/wafv2"
)

func init() {
	ProviderConfiguration.AddConfig(acm.Configure)
	ProviderConfiguration.AddConfig(acmpca.Configure)
	ProviderConfiguration.AddConfig(amp.Configure)
	ProviderConfiguration.AddConfig(apigateway.Configure)
	ProviderConfiguration.AddConfig(apigatewayv2.Configure)
	ProviderConfiguration.AddConfig(apprunner.Configure)
	ProviderConfiguration.AddConfig(appstream.Configure)
	ProviderConfiguration.AddConfig(athena.Configure)
	ProviderConfiguration.AddConfig(autoscaling.Configure)
	ProviderConfiguration.AddConfig(backup.Configure)
	ProviderConfiguration.AddConfig(batch.Configure)
	ProviderConfiguration.AddConfig(cloudfront.Configure)
	ProviderConfiguration.AddConfig(cloudsearch.Configure)
	ProviderConfiguration.AddConfig(cloudwatch.Configure)
	ProviderConfiguration.AddConfig(cloudwatchlogs.Configure)
	ProviderConfiguration.AddConfig(codeartifact.Configure)
	ProviderConfiguration.AddConfig(cognitoidentity.Configure)
	ProviderConfiguration.AddConfig(cognitoidp.Configure)
	ProviderConfiguration.AddConfig(connect.Configure)
	ProviderConfiguration.AddConfig(cur.Configure)
	ProviderConfiguration.AddConfig(datasync.Configure)
	ProviderConfiguration.AddConfig(dax.Configure)
	ProviderConfiguration.AddConfig(devicefarm.Configure)
	ProviderConfiguration.AddConfig(dms.Configure)
	ProviderConfiguration.AddConfig(docdb.Configure)
	ProviderConfiguration.AddConfig(dynamodb.Configure)
	ProviderConfiguration.AddConfig(ebs.Configure)
	ProviderConfiguration.AddConfig(ec2.Configure)
	ProviderConfiguration.AddConfig(ecr.Configure)
	ProviderConfiguration.AddConfig(ecrpublic.Configure)
	ProviderConfiguration.AddConfig(ecs.Configure)
	ProviderConfiguration.AddConfig(efs.Configure)
	ProviderConfiguration.AddConfig(eks.Configure)
	ProviderConfiguration.AddConfig(elasticache.Configure)
	ProviderConfiguration.AddConfig(elb.Configure)
	ProviderConfiguration.AddConfig(elbv2.Configure)
	ProviderConfiguration.AddConfig(firehose.Configure)
	ProviderConfiguration.AddConfig(gamelift.Configure)
	ProviderConfiguration.AddConfig(globalaccelerator.Configure)
	ProviderConfiguration.AddConfig(glue.Configure)
	ProviderConfiguration.AddConfig(grafana.Configure)
	ProviderConfiguration.AddConfig(iam.Configure)
	ProviderConfiguration.AddConfig(kafka.Configure)
	ProviderConfiguration.AddConfig(kafkaconnect.Configure)
	ProviderConfiguration.AddConfig(kinesis.Configure)
	ProviderConfiguration.AddConfig(kinesisanalytics.Configure)
	ProviderConfiguration.AddConfig(kinesisanalytics2.Configure)
	ProviderConfiguration.AddConfig(kms.Configure)
	ProviderConfiguration.AddConfig(lakeformation.Configure)
	ProviderConfiguration.AddConfig(lambda.Configure)
	ProviderConfiguration.AddConfig(licensemanager.Configure)
	ProviderConfiguration.AddConfig(memorydb.Configure)
	ProviderConfiguration.AddConfig(mq.Configure)
	ProviderConfiguration.AddConfig(mwaa.Configure)
	ProviderConfiguration.AddConfig(neptune.Configure)
	ProviderConfiguration.AddConfig(networkfirewall.Configure)
	ProviderConfiguration.AddConfig(opensearch.Configure)
	ProviderConfiguration.AddConfig(opensearchserverless.Configure)
	ProviderConfiguration.AddConfig(ram.Configure)
	ProviderConfiguration.AddConfig(rds.Configure)
	ProviderConfiguration.AddConfig(redshift.Configure)
	ProviderConfiguration.AddConfig(rolesanywhere.Configure)
	ProviderConfiguration.AddConfig(route53.Configure)
	ProviderConfiguration.AddConfig(route53resolver.Configure)
	ProviderConfiguration.AddConfig(route53recoverycontrolconfig.Configure)
	ProviderConfiguration.AddConfig(s3.Configure)
	ProviderConfiguration.AddConfig(secretsmanager.Configure)
	ProviderConfiguration.AddConfig(servicecatalog.Configure)
	ProviderConfiguration.AddConfig(organization.Configure)
	ProviderConfiguration.AddConfig(cloudwatchevents.Configure)
	ProviderConfiguration.AddConfig(budgets.Configure)
	ProviderConfiguration.AddConfig(servicediscovery.Configure)
	ProviderConfiguration.AddConfig(sfn.Configure)
	ProviderConfiguration.AddConfig(sns.Configure)
	ProviderConfiguration.AddConfig(sqs.Configure)
	ProviderConfiguration.AddConfig(transfer.Configure)
	ProviderConfiguration.AddConfig(directconnect.Configure)
	ProviderConfiguration.AddConfig(ds.Configure)
	ProviderConfiguration.AddConfig(dsql.Configure)
	ProviderConfiguration.AddConfig(qldb.Configure)
	ProviderConfiguration.AddConfig(fsx.Configure)
	ProviderConfiguration.AddConfig(networkmanager.Configure)
	ProviderConfiguration.AddConfig(sagemaker.Configure)
	ProviderConfiguration.AddConfig(redshiftserverless.Configure)
	ProviderConfiguration.AddConfig(kendra.Configure)
	ProviderConfiguration.AddConfig(medialive.Configure)
	ProviderConfiguration.AddConfig(ssoadmin.Configure)
	ProviderConfiguration.AddConfig(identitystore.Configure)
	ProviderConfiguration.AddConfig(iot.Configure)
	ProviderConfiguration.AddConfig(cloudformation.Configure)
	ProviderConfiguration.AddConfig(wafv2.Configure)
	ProviderConfiguration.AddConfig(verifiedaccess.Configure)
	ProviderConfiguration.AddConfig(vpclattice.Configure)
}
