# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: ecr.aws.upbound.io/v1beta1
kind: RepositoryCreationTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: ecr/v1beta1/repositorycreationtemplate
  name: rct-global-template
spec:
  forProvider:
    region: us-east-1
    prefix: "GLOBAL"
    appliedFor:
      - PULL_THROUGH_CACHE
    imageTagMutability: IMMUTABLE
    resourceTags:
      Scope: "cluster"
      Purpose: "global-template"


