# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBTargetGroup
metadata:
  name: test
  labels:
    testing.upbound.io/example-name: elbv2
spec:
  forProvider:
    name: example-lb-tg
    targetType: ip
    port: 80
    protocol: HTTP
    region: us-west-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: elbv2
---
apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBTargetGroupAttachment
metadata:
  name: test
  labels:
    testing.upbound.io/example-name: elbv2
spec:
  forProvider:
    port: 80
    region: us-west-1
    targetGroupArnSelector:
      matchLabels:
        testing.upbound.io/example-name: elbv2
    targetId: 172.16.10.25
    availabilityZone: us-west-1a

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: elbv2/v1beta2/lblistenerrule
  labels:
    testing.upbound.io/example-name: elbv2
  name: elbv2-vpc
spec:
  forProvider:
    cidrBlock: 172.16.0.0/16
    region: us-west-1
    tags:
      Name: DemoVpc

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    testing.upbound.io/example-name: elbv2
  name: elbv2-subnet
spec:
  forProvider:
    availabilityZone: us-west-1a
    cidrBlock: 172.16.10.0/24
    region: us-west-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: elbv2
