/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type UserPoolUICustomizationObservation struct {
	CSSVersion *string `json:"cssVersion,omitempty" tf:"css_version,omitempty"`

	CreationDate *string `json:"creationDate,omitempty" tf:"creation_date,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	ImageURL *string `json:"imageUrl,omitempty" tf:"image_url,omitempty"`

	LastModifiedDate *string `json:"lastModifiedDate,omitempty" tf:"last_modified_date,omitempty"`
}

type UserPoolUICustomizationParameters struct {

	// +kubebuilder:validation:Optional
	CSS *string `json:"css,omitempty" tf:"css,omitempty"`

	// +crossplane:generate:reference:type=UserPoolClient
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// +kubebuilder:validation:Optional
	ClientIDRef *v1.Reference `json:"clientIdRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	ClientIDSelector *v1.Selector `json:"clientIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	ImageFile *string `json:"imageFile,omitempty" tf:"image_file,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +terrajet:crd:field:TFTag=-
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"-"`

	// +crossplane:generate:reference:type=UserPool
	// +kubebuilder:validation:Optional
	UserPoolID *string `json:"userPoolId,omitempty" tf:"user_pool_id,omitempty"`

	// +kubebuilder:validation:Optional
	UserPoolIDRef *v1.Reference `json:"userPoolIdRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	UserPoolIDSelector *v1.Selector `json:"userPoolIdSelector,omitempty" tf:"-"`
}

// UserPoolUICustomizationSpec defines the desired state of UserPoolUICustomization
type UserPoolUICustomizationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserPoolUICustomizationParameters `json:"forProvider"`
}

// UserPoolUICustomizationStatus defines the observed state of UserPoolUICustomization.
type UserPoolUICustomizationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserPoolUICustomizationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// UserPoolUICustomization is the Schema for the UserPoolUICustomizations API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type UserPoolUICustomization struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserPoolUICustomizationSpec   `json:"spec"`
	Status            UserPoolUICustomizationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserPoolUICustomizationList contains a list of UserPoolUICustomizations
type UserPoolUICustomizationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserPoolUICustomization `json:"items"`
}

// Repository type metadata.
var (
	UserPoolUICustomization_Kind             = "UserPoolUICustomization"
	UserPoolUICustomization_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserPoolUICustomization_Kind}.String()
	UserPoolUICustomization_KindAPIVersion   = UserPoolUICustomization_Kind + "." + CRDGroupVersion.String()
	UserPoolUICustomization_GroupVersionKind = CRDGroupVersion.WithKind(UserPoolUICustomization_Kind)
)

func init() {
	SchemeBuilder.Register(&UserPoolUICustomization{}, &UserPoolUICustomizationList{})
}
