# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cloudfront.aws.m.upbound.io/v1beta1
kind: KeyValueStore
metadata:
  annotations:
    meta.upbound.io/example-id: cloudfront/v1beta1/keyvaluestore
  labels:
    testing.upbound.io/example-name: example-kvs-ns
  name: example-kvs-ns
  namespace: upbound-system
spec:
  forProvider:
    comment: Example key value store
---
apiVersion: cloudfront.aws.m.upbound.io/v1beta1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: cloudfront/v1beta1/keyvaluestore
  labels:
    testing.upbound.io/example-name: example-kvs-function-ns
  name: example-kvs-function-ns
  namespace: upbound-system
spec:
  forProvider:
    codeSecretRef:
      name: kvs-function-code-ns
      key: code
    comment: Reads the associated key value store
    keyValueStoreAssociationsSelector:
      matchLabels:
        testing.upbound.io/example-name: example-kvs-ns
    publish: true
    runtime: cloudfront-js-2.0
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: cloudfront/v1beta1/keyvaluestore
  name: kvs-function-code-ns
  namespace: upbound-system
type: Opaque
stringData:
  code: |
    import cf from 'cloudfront';
    const kvs = cf.kvs();
    async function handler(event) {
      const path = await kvs.get(event.request.uri).catch(() => null);
      if (path) event.request.uri = path;
      return event.request;
    }
