// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: CC0-1.0

package config

import (
	"github.com/crossplane-contrib/provider-upjet-aws/config/acm"
	"github.com/crossplane-contrib/provider-upjet-aws/config/acmpca"
	"github.com/crossplane-contrib/provider-upjet-aws/config/apigateway"
	"github.com/crossplane-contrib/provider-upjet-aws/config/apigatewayv2"
	"github.com/crossplane-contrib/provider-upjet-aws/config/apprunner"
	"github.com/crossplane-contrib/provider-upjet-aws/config/appstream"
	"github.com/crossplane-contrib/provider-upjet-aws/config/athena"
	"github.com/crossplane-contrib/provider-upjet-aws/config/autoscaling"
	"github.com/crossplane-contrib/provider-upjet-aws/config/backup"
	"github.com/crossplane-contrib/provider-upjet-aws/config/budgets"
	"github.com/crossplane-contrib/provider-upjet-aws/config/cloudformation"
	"github.com/crossplane-contrib/provider-upjet-aws/config/cloudfront"
	"github.com/crossplane-contrib/provider-upjet-aws/config/cloudsearch"
	"github.com/crossplane-contrib/provider-upjet-aws/config/cloudwatch"
	"github.com/crossplane-contrib/provider-upjet-aws/config/cloudwatchevents"
	"github.com/crossplane-contrib/provider-upjet-aws/config/cloudwatchlogs"
	"github.com/crossplane-contrib/provider-upjet-aws/config/cognitoidentity"
	"github.com/crossplane-contrib/provider-upjet-aws/config/cognitoidp"
	"github.com/crossplane-contrib/provider-upjet-aws/config/connect"
	"github.com/crossplane-contrib/provider-upjet-aws/config/cur"
	"github.com/crossplane-contrib/provider-upjet-aws/config/datasync"
	"github.com/crossplane-contrib/provider-upjet-aws/config/dax"
	"github.com/crossplane-contrib/provider-upjet-aws/config/devicefarm"
	"github.com/crossplane-contrib/provider-upjet-aws/config/directconnect"
	"github.com/crossplane-contrib/provider-upjet-aws/config/dms"
	"github.com/crossplane-contrib/provider-upjet-aws/config/docdb"
	"github.com/crossplane-contrib/provider-upjet-aws/config/ds"
	"github.com/crossplane-contrib/provider-upjet-aws/config/dynamodb"
	"github.com/crossplane-contrib/provider-upjet-aws/config/ebs"
	"github.com/crossplane-contrib/provider-upjet-aws/config/ec2"
	"github.com/crossplane-contrib/provider-upjet-aws/config/ecr"
	"github.com/crossplane-contrib/provider-upjet-aws/config/ecrpublic"
	"github.com/crossplane-contrib/provider-upjet-aws/config/ecs"
	"github.com/crossplane-contrib/provider-upjet-aws/config/efs"
	"github.com/crossplane-contrib/provider-upjet-aws/config/eks"
	"github.com/crossplane-contrib/provider-upjet-aws/config/elasticache"
	"github.com/crossplane-contrib/provider-upjet-aws/config/elb"
	"github.com/crossplane-contrib/provider-upjet-aws/config/elbv2"
	"github.com/crossplane-contrib/provider-upjet-aws/config/firehose"
	"github.com/crossplane-contrib/provider-upjet-aws/config/fsx"
	"github.com/crossplane-contrib/provider-upjet-aws/config/gamelift"
	"github.com/crossplane-contrib/provider-upjet-aws/config/globalaccelerator"
	"github.com/crossplane-contrib/provider-upjet-aws/config/glue"
	"github.com/crossplane-contrib/provider-upjet-aws/config/grafana"
	"github.com/crossplane-contrib/provider-upjet-aws/config/iam"
	"github.com/crossplane-contrib/provider-upjet-aws/config/identitystore"
	"github.com/crossplane-contrib/provider-upjet-aws/config/iot"
	"github.com/crossplane-contrib/provider-upjet-aws/config/kafka"
	"github.com/crossplane-contrib/provider-upjet-aws/config/kafkaconnect"
	"github.com/crossplane-contrib/provider-upjet-aws/config/kendra"
	"github.com/crossplane-contrib/provider-upjet-aws/config/kinesis"
	"github.com/crossplane-contrib/provider-upjet-aws/config/kinesisanalytics"
	kinesisanalytics2 "github.com/crossplane-contrib/provider-upjet-aws/config/kinesisanalyticsv2"
	"github.com/crossplane-contrib/provider-upjet-aws/config/kms"
	"github.com/crossplane-contrib/provider-upjet-aws/config/lakeformation"
	"github.com/crossplane-contrib/provider-upjet-aws/config/lambda"
	"github.com/crossplane-contrib/provider-upjet-aws/config/licensemanager"
	"github.com/crossplane-contrib/provider-upjet-aws/config/medialive"
	"github.com/crossplane-contrib/provider-upjet-aws/config/memorydb"
	"github.com/crossplane-contrib/provider-upjet-aws/config/mq"
	"github.com/crossplane-contrib/provider-upjet-aws/config/neptune"
	"github.com/crossplane-contrib/provider-upjet-aws/config/networkfirewall"
	"github.com/crossplane-contrib/provider-upjet-aws/config/networkmanager"
	"github.com/crossplane-contrib/provider-upjet-aws/config/opensearch"
	"github.com/crossplane-contrib/provider-upjet-aws/config/opensearchserverless"
	"github.com/crossplane-contrib/provider-upjet-aws/config/opsworks"
	"github.com/crossplane-contrib/provider-upjet-aws/config/organization"
	"github.com/crossplane-contrib/provider-upjet-aws/config/qldb"
	"github.com/crossplane-contrib/provider-upjet-aws/config/ram"
	"github.com/crossplane-contrib/provider-upjet-aws/config/rds"
	"github.com/crossplane-contrib/provider-upjet-aws/config/redshift"
	"github.com/crossplane-contrib/provider-upjet-aws/config/redshiftserverless"
	"github.com/crossplane-contrib/provider-upjet-aws/config/rolesanywhere"
	"github.com/crossplane-contrib/provider-upjet-aws/config/route53"
	"github.com/crossplane-contrib/provider-upjet-aws/config/route53recoverycontrolconfig"
	"github.com/crossplane-contrib/provider-upjet-aws/config/route53resolver"
	"github.com/crossplane-contrib/provider-upjet-aws/config/s3"
	"github.com/crossplane-contrib/provider-upjet-aws/config/sagemaker"
	"github.com/crossplane-contrib/provider-upjet-aws/config/secretsmanager"
	"github.com/crossplane-contrib/provider-upjet-aws/config/servicecatalog"
	"github.com/crossplane-contrib/provider-upjet-aws/config/servicediscovery"
	"github.com/crossplane-contrib/provider-upjet-aws/config/sfn"
	"github.com/crossplane-contrib/provider-upjet-aws/config/sns"
	"github.com/crossplane-contrib/provider-upjet-aws/config/sqs"
	"github.com/crossplane-contrib/provider-upjet-aws/config/ssoadmin"
	"github.com/crossplane-contrib/provider-upjet-aws/config/transfer"
)

func init() {
	ProviderConfiguration.AddConfig(acm.Configure)
	ProviderConfiguration.AddConfig(acmpca.Configure)
	ProviderConfiguration.AddConfig(apigateway.Configure)
	ProviderConfiguration.AddConfig(apigatewayv2.Configure)
	ProviderConfiguration.AddConfig(apprunner.Configure)
	ProviderConfiguration.AddConfig(appstream.Configure)
	ProviderConfiguration.AddConfig(athena.Configure)
	ProviderConfiguration.AddConfig(autoscaling.Configure)
	ProviderConfiguration.AddConfig(backup.Configure)
	ProviderConfiguration.AddConfig(cloudfront.Configure)
	ProviderConfiguration.AddConfig(cloudsearch.Configure)
	ProviderConfiguration.AddConfig(cloudwatch.Configure)
	ProviderConfiguration.AddConfig(cloudwatchlogs.Configure)
	ProviderConfiguration.AddConfig(cognitoidentity.Configure)
	ProviderConfiguration.AddConfig(cognitoidp.Configure)
	ProviderConfiguration.AddConfig(connect.Configure)
	ProviderConfiguration.AddConfig(cur.Configure)
	ProviderConfiguration.AddConfig(datasync.Configure)
	ProviderConfiguration.AddConfig(dax.Configure)
	ProviderConfiguration.AddConfig(devicefarm.Configure)
	ProviderConfiguration.AddConfig(dms.Configure)
	ProviderConfiguration.AddConfig(docdb.Configure)
	ProviderConfiguration.AddConfig(dynamodb.Configure)
	ProviderConfiguration.AddConfig(ebs.Configure)
	ProviderConfiguration.AddConfig(ec2.Configure)
	ProviderConfiguration.AddConfig(ecr.Configure)
	ProviderConfiguration.AddConfig(ecrpublic.Configure)
	ProviderConfiguration.AddConfig(ecs.Configure)
	ProviderConfiguration.AddConfig(efs.Configure)
	ProviderConfiguration.AddConfig(eks.Configure)
	ProviderConfiguration.AddConfig(elasticache.Configure)
	ProviderConfiguration.AddConfig(elb.Configure)
	ProviderConfiguration.AddConfig(elbv2.Configure)
	ProviderConfiguration.AddConfig(firehose.Configure)
	ProviderConfiguration.AddConfig(gamelift.Configure)
	ProviderConfiguration.AddConfig(globalaccelerator.Configure)
	ProviderConfiguration.AddConfig(glue.Configure)
	ProviderConfiguration.AddConfig(grafana.Configure)
	ProviderConfiguration.AddConfig(iam.Configure)
	ProviderConfiguration.AddConfig(kafka.Configure)
	ProviderConfiguration.AddConfig(kafkaconnect.Configure)
	ProviderConfiguration.AddConfig(kinesis.Configure)
	ProviderConfiguration.AddConfig(kinesisanalytics.Configure)
	ProviderConfiguration.AddConfig(kinesisanalytics2.Configure)
	ProviderConfiguration.AddConfig(kms.Configure)
	ProviderConfiguration.AddConfig(lakeformation.Configure)
	ProviderConfiguration.AddConfig(lambda.Configure)
	ProviderConfiguration.AddConfig(licensemanager.Configure)
	ProviderConfiguration.AddConfig(memorydb.Configure)
	ProviderConfiguration.AddConfig(mq.Configure)
	ProviderConfiguration.AddConfig(neptune.Configure)
	ProviderConfiguration.AddConfig(networkfirewall.Configure)
	ProviderConfiguration.AddConfig(opensearch.Configure)
	ProviderConfiguration.AddConfig(opensearchserverless.Configure)
	ProviderConfiguration.AddConfig(ram.Configure)
	ProviderConfiguration.AddConfig(rds.Configure)
	ProviderConfiguration.AddConfig(redshift.Configure)
	ProviderConfiguration.AddConfig(rolesanywhere.Configure)
	ProviderConfiguration.AddConfig(route53.Configure)
	ProviderConfiguration.AddConfig(route53resolver.Configure)
	ProviderConfiguration.AddConfig(route53recoverycontrolconfig.Configure)
	ProviderConfiguration.AddConfig(s3.Configure)
	ProviderConfiguration.AddConfig(secretsmanager.Configure)
	ProviderConfiguration.AddConfig(servicecatalog.Configure)
	ProviderConfiguration.AddConfig(organization.Configure)
	ProviderConfiguration.AddConfig(cloudwatchevents.Configure)
	ProviderConfiguration.AddConfig(budgets.Configure)
	ProviderConfiguration.AddConfig(servicediscovery.Configure)
	ProviderConfiguration.AddConfig(sfn.Configure)
	ProviderConfiguration.AddConfig(sns.Configure)
	ProviderConfiguration.AddConfig(sqs.Configure)
	ProviderConfiguration.AddConfig(transfer.Configure)
	ProviderConfiguration.AddConfig(directconnect.Configure)
	ProviderConfiguration.AddConfig(ds.Configure)
	ProviderConfiguration.AddConfig(qldb.Configure)
	ProviderConfiguration.AddConfig(fsx.Configure)
	ProviderConfiguration.AddConfig(networkmanager.Configure)
	ProviderConfiguration.AddConfig(opsworks.Configure)
	ProviderConfiguration.AddConfig(sagemaker.Configure)
	ProviderConfiguration.AddConfig(redshiftserverless.Configure)
	ProviderConfiguration.AddConfig(kendra.Configure)
	ProviderConfiguration.AddConfig(medialive.Configure)
	ProviderConfiguration.AddConfig(ssoadmin.Configure)
	ProviderConfiguration.AddConfig(identitystore.Configure)
	ProviderConfiguration.AddConfig(iot.Configure)
	ProviderConfiguration.AddConfig(cloudformation.Configure)
}
