# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: route53profiles.aws.m.upbound.io/v1beta1
kind: ResourceAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: route53profiles/v1beta1/resourceassociation
    upjet.upbound.io/manual-intervention: | 
      resourceArn does not support reference fields due to multiple
      valid referenceable kinds. Needs to be manually set to the private hosted zone
      ARN, via compositions or manually.
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    name: example
    profileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
    # for this example manifest, manually set the zone ARN after it is available
    resourceArn: "arn:aws:route53:::hostedzone/Z01234567ABABA0123A01"
---

apiVersion: route53.aws.m.upbound.io/v1beta1
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: route53profiles/v1beta1/resourceassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    name: mycompanydemo.test
    vpc:
    - vpcIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      vpcRegion: us-west-1

---

apiVersion: route53profiles.aws.m.upbound.io/v1beta1
kind: Profile
metadata:
  annotations:
    meta.upbound.io/example-id: route53profiles/v1beta1/resourceassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    name: example
    region: us-west-1

---

apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: route53profiles/v1beta1/resourceassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    region: us-west-1
    cidrBlock: 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
