# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  name: example-codebuild-reports
  labels:
    testing.upbound.io/example-name: example-codebuild-reportgroup
spec:
  forProvider:
    region: us-west-1
---
apiVersion: codebuild.aws.m.upbound.io/v1beta1
kind: ReportGroup
metadata:
  name: example
  annotations:
    meta.upbound.io/example-id: codebuild/v1beta1/reportgroup
  labels:
    testing.upbound.io/example-name: example-codebuild-reportgroup
spec:
  forProvider:
    region: us-west-1
    name: example-report-group
    type: TEST
    exportConfig:
      - type: S3
        s3Destination:
          - bucketSelector:
              matchLabels:
                testing.upbound.io/example-name: example-codebuild-reportgroup
            encryptionDisabled: false
            packaging: NONE
