# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: lambdamicrovms.aws.upbound.io/v1beta1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: lambdamicrovms/v1beta1/image
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    baseImageArn: arn:${data.aws_partition.current.partition}:lambda:${data.aws_region.current.region}:aws:microvm-image:al2023-1
    buildRoleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    codeArtifact:
      uriSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    name: example
    region: us-west-1

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: lambdamicrovms/v1beta1/image
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    assumeRolePolicy: |-
      ${jsonencode({
          Version = "2012-10-17"
          Statement = [{
            Action = "sts:AssumeRole"
            Effect = "Allow"
            Principal = {
              Service = "lambda.amazonaws.com"
            }
          }]
        })}
    region: us-west-1

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: lambdamicrovms/v1beta1/image
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    policy: |-
      ${jsonencode({
          Version = "2012-10-17"
          Statement = [{
            Action   = ["s3:GetObject"]
            Effect   = "Allow"
            Resource = "${aws_s3_bucket.example.arn}/*"
          }]
        })}
    region: us-west-1
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: s3.aws.upbound.io/v1beta2
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: lambdamicrovms/v1beta1/image
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1

---

apiVersion: s3.aws.upbound.io/v1beta2
kind: Object
metadata:
  annotations:
    meta.upbound.io/example-id: lambdamicrovms/v1beta1/image
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    key: code.zip
    region: us-west-1
    source: code.zip
