# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: bedrock.aws.m.upbound.io/v1beta1
kind: EvaluationJob
metadata:
  annotations:
    meta.upbound.io/example-id: bedrock/v1beta1/evaluationjob
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    evaluationConfig:
      automated:
        datasetMetricConfig:
        - dataset:
            name: Builtin.Bold
          metricNames:
          - Builtin.Robustness
          taskType: Generation
    inferenceConfig:
      model:
      - bedrockModel:
          modelIdentifier: amazon.nova-micro-v1:0
    jobName: example-job
    outputDataConfig:
      s3Uri: s3://${aws_s3_bucket.example.id}/output/
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
