# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: s3vectors.aws.upbound.io/v1beta1
kind: VectorBucketPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: s3vectors/v1beta1/vectorbucketpolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Id": "writePolicy",
        "Statement": [{
          "Sid": "writeStatement",
          "Effect": "Allow",
          "Principal": {
            "AWS": "123456789012"
          },
          "Action": [
            "s3vectors:PutVectors"
          ],
          "Resource": "*"
        }]
      }
    region: us-west-1
    vectorBucketArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
