# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: cloudwatchlogs.aws.upbound.io/v1beta1
kind: AccountPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: cloudwatchlogs/v1beta1/accountpolicy
  labels:
    testing.upbound.io/example-name: data_protection
  name: data-protection
spec:
  forProvider:
    policyDocument: |-
      ${jsonencode({
          Name    = "DataProtection"
          Version = "2021-06-01"

          Statement = [
            {
              Sid            = "Audit"
              DataIdentifier = ["arn:aws:dataprotection::aws:data-identifier/EmailAddress"]
              Operation = {
                Audit = {
                  FindingsDestination = {}
                }
              }
            },
            {
              Sid            = "Redact"
              DataIdentifier = ["arn:aws:dataprotection::aws:data-identifier/EmailAddress"]
              Operation = {
                Deidentify = {
                  MaskConfig = {}
                }
              }
            }
          ]
        })}
    policyName: data-protection
    policyType: DATA_PROTECTION_POLICY
    region: us-west-1
