#!/usr/bin/env bash

set -aeuo pipefail

# skip the config directory argument
shift
output_dir="$1"

cd "${output_dir}"
# prepend the YAML doc separator to the stdin
{ echo "---"; cat; } | ${YQ} --split-exp '.spec.group + "_" + .spec.names.plural + ".yaml"' -
