# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: quicksight.aws.upbound.io/v1beta1
kind: DataSource
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/datasource
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    dataSourceId: example-id
    name: My Cool Data in S3
    parameters:
      s3:
        manifestFileLocation:
          bucketSelector:
            matchLabels:
              testing.upbound.io/example-name: example
          keySelector:
            matchLabels:
              testing.upbound.io/example-name: example
    region: us-west-1
    type: S3
