# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: eks.aws.m.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/podidentityassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    clusterNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    disableSessionTags: true
    namespace: example
    policy: |-
      ${jsonencode({
          Version = "2012-10-17"
          Statement = [{
            Effect   = "Allow"
            Action   = ["s3:GetObject"]
            Resource = "arn:aws:s3:::my-bucket/*"
          }]
        })}
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceAccount: example-sa
